Add note on migration from old version
actualbudget/docs pull request #101
Opened 2023-02-09 07:12 UTC by hpfast

see #25 

It can be confusing for users of the old hosted Actual who want to migrate to the new self-hosted version, because the old Desktop app doesn't have the export button.

This PR adds a note to the Migration page about using the Web version which does have the export button, and links to it from the Installation overview.

2023-02-09 08:22 UTC, rich-howell requested changes

2023-02-09 08:22 UTC, rich-howell commented on docs/Getting-Started/migration/migration-intro.md
> +The Desktop app that was tied to the old hosted instance of ActualBudget does not have the export button which is available in the Web version and in newer versions of the Desktop app (see https://gi
We have documentation for exporting and importing your data, maybe they could be linked? In the relevant places.

https://actualbudget.github.io/docs/Backup-Restore/Backups
https://actualbudget.github.io/docs/Backup-Restore/Restore

2023-02-09 08:22 UTC, rich-howell commented on docs/Installing/overview.md
> +If you're coming from the old, hosted version of Actual, you may want to [migrate your data](../Getting-Started/migration/migration-intro.md).
I think we need to be more specific on what the old, hosted version is. Maybe "If you're coming from a managed Actual subscription"

2023-02-09 13:36 UTC, j-f1 commented on docs/Getting-Started/migration/migration-intro.md
> +The Desktop app that was tied to the old hosted instance of ActualBudget does not have the export button which is available in the Web version and in newer versions of the Desktop app (see https://gi
I believe it’s also possible to zip up your budget folder (which by default is in `~/Documents/Actual/My-Budget-abc123` on macOS and probably somewhere similar on other platforms)

2023-02-09 20:50 UTC, hpfast commented
oops @j-f1 , I 'resolved the conversation' by accident. Good point about being more specific. I'll address that.

2023-02-09 20:52 UTC, hpfast commented on docs/Installing/overview.md
> +If you're coming from the old, hosted version of Actual, you may want to [migrate your data](../Getting-Started/migration/migration-intro.md).
Good point. I think it will apply specifically to the original app.actualbudget.com, so how about this:

```suggestion
If you're coming from the original, managed Actual subscription service, you may want to [migrate your data](../Getting-Started/migration/migration-intro.md).
```

2023-02-09 21:08 UTC, hpfast commented on docs/Getting-Started/migration/migration-intro.md
> +The Desktop app that was tied to the old hosted instance of ActualBudget does not have the export button which is available in the Web version and in newer versions of the Desktop app (see https://gi
Thanks. I see that the backup-restore docs already draw attention to the fact that some export functionality is only available in the Web version. Perhaps, the following:

```suggestion
:::note
Are you coming from the original, managed Actual subscription service? That used an older version of the desktop app which doesn't have the export button, but you can log in to the Web version at app.actualbudget.com to export your data in a format suitable for importing in your new instance. See [Backups](https://actualbudget.github.io/docs/Backup-Restore/Backups) and [Restoring](https://actualbudget.github.io/docs/Backup-restore/Restore).

Instead of creating an export from the Web app, you can also create a zip archive of your budget folder, which is equivalent. The folder is located at `~/Documents/Actual/My-Budget-abc123` by default on MacOS and Linux. The resulting zip file can be imported into Actual via the Web app.
```

Windows default location ... ?

2023-02-15 23:23 UTC, rich-howell commented
Thanks for the changes on this @hpfast I am going to merge this in it's current state and we can work out the detail later.

2023-02-15 23:23 UTC, merged