using actual (images and instructions update) #85
actualbudget/docs pull request #109
Opened 2023-03-04 13:06 UTC by tjex

Updated images and instructions in the 'Using Actual' section. 
Mostly all changes based on the new sidebar layout. 

Also did some file keeping (making folders for images and deleted old images)

The small screenshots still render (unnecessarily) large, I'm not sure how to address that in markdown. 
Happy to update if needed.

2023-03-04 13:29 UTC, j-f1 commented
Updated pages:

- https://deploy-preview-109--zingy-bonbon-b1b286.netlify.app/Accounts/overview
- https://deploy-preview-109--zingy-bonbon-b1b286.netlify.app/accounts/addaccount
- https://deploy-preview-109--zingy-bonbon-b1b286.netlify.app/Backup-Restore/Backups
- https://deploy-preview-109--zingy-bonbon-b1b286.netlify.app/Budgeting/returnsandreimbursements

> The small screenshots still render (unnecessarily) large, I'm not sure how to address that in markdown.

You can always use an HTML `<img>` tag (e.g. `<img src="foo/bar.png" width="500">`. That said I’m gonna take a look at ways to handle this automatically.

2023-03-04 13:39 UTC, j-f1 commented
Thank you for opening this PR!

Updated pages:
- https://deploy-preview-109--zingy-bonbon-b1b286.netlify.app/Accounts/overview
- https://deploy-preview-109--zingy-bonbon-b1b286.netlify.app/Accounts/addaccount
- https://deploy-preview-109--zingy-bonbon-b1b286.netlify.app/Backup-Restore/Backups
- https://deploy-preview-109--zingy-bonbon-b1b286.netlify.app/Budgeting/returnsandreimbursements

> The small screenshots still render (unnecessarily) large, I'm not sure how to address that in markdown. Happy to update if needed.

I’ll open a PR shortly to build some tools to help with that!

2023-03-04 15:12 UTC, j-f1 commented
Opened https://github.com/actualbudget/docs/pull/110 — once that’s merged, you’ll be able to add `@2x` to all of your Retina screenshots to get them to size properly.

2023-03-04 16:55 UTC, rich-howell commented
Hey @tjex 

Thanks so much for this, fantastic work. 

> Opened #110 — once that’s merged, you’ll be able to add `@2x` to all of your Retina screenshots to get them to size properly.

This is merged.

2023-03-04 18:49 UTC, tjex commented
glad to be able to give something back :)
unfortunately after merging the current master to my local branch, there is some weird height stretching going on with the images. And it looks like it's effecting the screenshots from retina screens only... 
Will comment in #110

2023-03-04 18:59 UTC, j-f1 commented
Pushed a commit to hopefully fix it!

2023-03-04 19:02 UTC, tjex commented
it did :)

2023-03-04 19:08 UTC, tjex commented
trying with `![@2x](/img/accounts/SidebarAccountList.png)` but seeing no change.
will push in case it should be looked at.

2023-03-04 19:16 UTC, j-f1 commented
Sorry, I wasn’t super clear — you’ll need to rename the files on disk to include the suffix and then use this syntax: `![](/img/accounts/SidebarAccountList@2x.png)`

2023-03-05 08:12 UTC, tjex commented
@rich-howell and @j-f1 
ready for review / merging - except that the CI has failed now all of a sudden. 
I checked and my local branch is up to date with master.

2023-03-05 10:36 UTC, rich-howell commented
> @rich-howell and @j-f1 ready for review / merging - except that the CI has failed now all of a sudden. I checked and my local branch is up to date with master.

`8:09:33 AM: Module not found: Error: Can't resolve '/img/backup-restore/sidebar-settings@2x.png' in '/opt/build/repo/docs/Backup-Restore'`

2023-03-05 10:37 UTC, rich-howell requested changes

2023-03-05 10:37 UTC, rich-howell commented on docs/Backup-Restore/Backups.md
> +   ![](/img/backup-restore/sidebar-settings@2x.png)
This file does not appear to exist.

2023-03-05 17:40 UTC, tjex commented on docs/Backup-Restore/Backups.md
> +   ![](/img/backup-restore/sidebar-settings@2x.png)
ahhh yeah. That folder got me a few times. 
Git ignores it because in the gitignore file there is an entry for `Backup*/`

Drove me bananas for a bit when ripgrepping too 😅

Anyway. just pushed it. 
Thanks!

2023-03-05 17:46 UTC, j-f1 commented
Will open a PR to clean that file up

2023-03-05 18:39 UTC, rich-howell approved these changes

2023-03-05 18:39 UTC, merged