Added documention about the header authentication
actualbudget/docs pull request #341
Opened 2024-03-28 16:03 UTC by joewashear007

2024-05-13 15:02 UTC, youngcw commented
@joewashear007 Would you be willing to take the steps you put into the client PR and add that here as well?

2024-05-21 14:07 UTC, joewashear007 commented
@youngcw can you review this? I have added more details on setting up this feature.

2024-05-21 15:32 UTC, youngcw commented on docs/advanced/http-header-auth.md
> +Client Version 25.x.0 and
We should set this to be 25.6.0 which would be the June release.

2024-05-21 15:54 UTC, joewashear007 commented on docs/advanced/http-header-auth.md
> +Client Version 25.x.0 and
duh... it is the simple things that get you :p

2024-05-22 18:51 UTC, youngcw approved these changes

2024-05-25 16:33 UTC, psybers requested changes

2024-05-25 16:33 UTC, psybers commented on docs/config/index.md
> +Change the authentication method for actual  (environment variable: `ACTUAL_LOGIN_METHOD`). The valid values are:
```suggestion
Change the authentication method for Actual  (environment variable: `ACTUAL_LOGIN_METHOD`). The valid values are: 
```

2024-05-25 16:33 UTC, psybers commented on docs/config/index.md
> +* "header" - Use the HTTP header `x-actual-password` to automatically login. This is advances used and is not done correctly could have security implications.
```suggestion
* `"password"` (default) - This is standard password authentication
* `"header"` - Use the HTTP header `x-actual-password` to automatically login. This is advances used and is not done correctly could have security implications. 
```

2024-05-25 16:33 UTC, psybers commented on docs/config/index.md
> +Config the clients that are allowed to authentic with http headers. This defaults to known internal ip ranges: `[10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7, ::1/128]`)  (environment variable
```suggestion
Config the clients that are allowed to authentic with HTTP headers. This defaults to known internal ip ranges: `[10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7, ::1/128]`  (environment variable: `ACTUAL_TRUSTED_PROXIES`, comma separated string).
```

2024-05-25 16:33 UTC, psybers commented on docs/advanced/http-header-auth.md
This page is not linked anywhere and can only be found via search.

Update this file to add it to the sidebar: https://github.com/actualbudget/docs/blob/master/docs-sidebar.js

Or link to it from another page.

2024-05-25 16:33 UTC, psybers commented on docs/advanced/http-header-auth.md
> +This feature will allow Actual to use a HTTP header to automatically authenticate and login without prompting for a password. This would be useful for individuals who run SSO services like [Authentik
```suggestion
This feature will allow Actual to use an HTTP header to automatically authenticate and log in without prompting for a password. This would be useful for individuals who run SSO services like [Authentik](https://goauthentik.io/), [Authelia](https://www.authelia.com/), and more.
```

2024-05-25 16:33 UTC, psybers commented on docs/advanced/http-header-auth.md
> +This feature needs to be enabled on the server, it is not configure to work out of the box. In the actual config, set the value `loginMethod` or env `ACTUAL_LOGIN_METHOD` to `"header"`. This will ena
```suggestion
This feature needs to be enabled on the server, it is not configured to work out of the box. In the Actual config, set the value `loginMethod` or env `ACTUAL_LOGIN_METHOD` to `"header"`. This will enable header authentication, but the normal password authentication will still work as a fallback. 
```

2024-05-25 16:33 UTC, psybers commented on docs/advanced/http-header-auth.md
> +This feature needs to be enabled on the server, it is not configure to work out of the box. In the actual config, set the value `loginMethod` or env `ACTUAL_LOGIN_METHOD` to `"header"`. This will ena
Should this maybe link to the other page describing `loginMehod`?

2024-05-25 16:33 UTC, psybers commented on docs/advanced/http-header-auth.md
> +Be careful! A misconfiguration on this next step could make your instance available to whole internet.
```suggestion
Be careful! A misconfiguration on this next step could make your instance available to the whole internet. 
```

2024-05-25 16:33 UTC, psybers commented on docs/advanced/http-header-auth.md
> +The SSO provider then needs to be configured to pass a extra HTTP header to actual. The details on how to do this are unique to the SSO provider, but the header `x-actual-password` needs to be set to
```suggestion
The SSO provider then needs to be configured to pass an extra HTTP header to Actual. The details on how to do this are unique to the SSO provider, but the header `x-actual-password` needs to be set to your actual password.
```

2024-05-25 16:33 UTC, psybers commented on docs/advanced/http-header-auth.md
> +This feature is not a HTTP basic auth, but a different form of using a password. For HTTP basic auth or User accounts see [this issue](https://github.com/actualbudget/actual/issues/524)
```suggestion
This feature is not an HTTP basic auth, but a different form of using a password. For HTTP basic auth or user accounts see [this issue](https://github.com/actualbudget/actual/issues/524)
```

2024-05-25 16:33 UTC, psybers commented on docs/advanced/http-header-auth.md
> +* `trustedProxies` (env: `ACTUAL_TRUSTED_PROXIES`): List of CIDRs to allowed to send the authentication header. The default value for this is to allow only known internal ip address ranges. If your S
This repeats the other page.  I would recommend removing it and providing a link to that page where it makes sense.

2024-05-30 02:15 UTC, joewashear007 commented on docs/advanced/http-header-auth.md
good catch

2024-05-30 02:18 UTC, psybers approved these changes

2024-06-03 14:06 UTC, youngcw approved these changes

2024-06-03 14:06 UTC, merged