add install info on desktop apps
actualbudget/docs pull request #354
Opened 2024-05-08 19:36 UTC by youngcw

2024-05-25 16:25 UTC, psybers requested changes

2024-05-25 16:25 UTC, psybers commented on docs/install/index.md
> +The standard way of using Actual is to setup a personal server and use a web browser for the application.  For quick testing or getting to know Actual before setting up a server, the [demo](https://d
When used as a verb, it is "set up" and not "setup".
```suggestion
The standard way of using Actual is to set up a personal server and use a web browser for the application.  For quick testing or getting to know Actual before setting up a server, the [demo](https://demo.actualbudget.org) or a [desktop application](https://github.com/actualbudget/actual/releases) are a good place to start.
```

2024-05-25 16:25 UTC, psybers commented on docs/install/index.md
> +## Server Optional Client Options
```suggestion
## Server-Optional Client Options
```

2024-05-25 16:25 UTC, psybers commented on docs/install/index.md
> +## Server Based Client Options
```suggestion
## Server-Based Client Options
```

2024-05-25 16:25 UTC, psybers commented on docs/install/index.md
> +The server provides a web based version of Actual.  This web app can be used in a browser as a standard web page to use view and edit your budget.  The web page can also be installed to your device.
```suggestion
The server provides a web-based version of Actual.  This web app can be used in a browser as a standard web page to view and edit your budget.  The web page can also be installed on your device.  For mobile devices, an installed web page will work offline.
```

2024-05-25 16:25 UTC, psybers commented on docs/install/index.md
> +* Offline use is ready out of the box
```suggestion
Desktop applications are available for Windows, Mac, and Linux. These can be [downloaded from GitHub](https://github.com/actualbudget/actual/releases).  The desktop apps have the following benefits:
* Can connect to a server (this gives them the ability to use the server-based features)
* Automated backups
* Offline use is ready out of the box 
```

2024-05-25 16:25 UTC, psybers commented on docs/install/index.md
> +[^2]: A portion of the cost to host on PikaPods is donated to the Actual Budget Project.  With that said, PikaPods is a very simple, and cost effective way, to host your server.
```suggestion
[^1]: You technically don't need a server instance for this. You need to run either a web-based client or a server, but a server is the same effort.
[^2]: A portion of the cost to host on PikaPods is donated to the Actual Budget Project.  With that said, PikaPods is a very simple, and cost-effective way, to host your server.
```

2024-05-25 20:26 UTC, psybers approved these changes
LGTM.

2024-06-03 16:31 UTC, carkom approved these changes
Looks good!

2024-06-03 16:45 UTC, merged