Update settings.md
actualbudget/docs pull request #370
Opened 2024-06-16 01:24 UTC by niceguy4

Updated experimental features to match what's listed in app.

2024-06-21 17:51 UTC, psybers requested changes

2024-06-21 17:51 UTC, psybers commented on docs/tour/settings.md
> +Be careful with this section; you might encounter irrecoverable errors if you enable these settings. But if you want to test out some bleeding-edge features, here's your place to do it. We _highly_ r
I'd recommend somewhat future-proofing this string.  It will be mostly accurate, and then just the list below needs maintained moving forward.

```suggestion
Be careful with this section; you might encounter irrecoverable errors if you enable these settings. But if you want to test out some bleeding-edge features, here's your place to do it. We _highly_ recommend backing up your budget before continuing, just in case. As of the [latest release](../releases.md), the current available experimental features are:
```

2024-06-28 18:23 UTC, youngcw approved these changes

2024-06-28 18:48 UTC, psybers approved these changes

2024-06-28 19:04 UTC, merged