Updated the local installation file
actualbudget/docs pull request #388
Opened 2024-07-04 21:28 UTC by codewithdev

This PR brings the following changes in the https://actualbudget.org/docs/install/local page.

<img width="1135" alt="image" src="https://github.com/actualbudget/docs/assets/44609609/0ec1833f-360f-474e-9f0a-337c7d003894">

- Updated the content structure of the entire page.
- Removed unnecessary information and content
- Removed superficial information.

2024-07-05 13:22 UTC, Teprifer reviewed
Some good formatting changes here. :)

2024-07-07 14:29 UTC, codewithdev commented
I will take a look at those review comments. Thanks for briefly reviewing this. Appreciate your efforts on this.

2024-07-08 09:32 UTC, RubenOlsen commented on docs/install/local.md
> +After the Actual server is started, you can access the Actual server from local server logged in the CLI as  [http://localhost:5006](http://localhost:5006).
I agree with @Teprifer - but I also like some of the proposed changes. 

What about _After the servers have started, you can access Actual using your browser at [http://localhost:5006](http://localhost:5006). _

This is a bit more to the point compared to the original text and maybe a less confusing that the proposed change.

2024-07-08 09:35 UTC, RubenOlsen commented on docs/install/local.md
> +To update with our latest releases, use `git pull` command from the `master` branch of your local directory of Actual. After updating the changes, execute the `yarn install` to download the latest up
I agree with @Teprifer - even if the proposed change is shorter, there are details that only seasoned people will understand, which is missing. We always need to remember that this part of the documentation is not necessarily for the "experts".

2024-07-10 20:35 UTC, codewithdev commented on docs/install/local.md
> +To update with our latest releases, use `git pull` command from the `master` branch of your local directory of Actual. After updating the changes, execute the `yarn install` to download the latest up
Got it @RubenOlsen

2024-07-19 20:22 UTC, codewithdev commented
Reviews have been incorporated.

2024-07-20 06:29 UTC, Teprifer commented on docs/install/local.md
> +After servers have started, you can access Actual using your browser at [http://localhost:5006](http://localhost:5006).
Slight tweak, should be 'server' singular, and has vs have, e.g.

After the server has been started

2024-07-26 19:33 UTC, RubenOlsen reviewed
Looking good to me.

2024-07-26 19:35 UTC, RubenOlsen approved these changes

2024-08-08 20:42 UTC, psybers requested changes

2024-08-08 20:42 UTC, psybers commented on docs/install/local.md
> +Actual is constantly evolving to include new features and improve user's experience. It is always recommended to update your local installation with our [latest releases](https://actualbudget.org/doc
```suggestion
Actual is constantly evolving to include new features and improve the user's experience. It is always recommended that your local installation be updated with our [latest releases](https://actualbudget.org/docs/releases).
```

2024-08-08 20:42 UTC, psybers commented on docs/install/local.md
> +1. Stop the server if it’s running. You can use the keyboard shortcut <kbd>"ctrl" </kbd> <kbd>"c" </kbd> (even on macOS) to stop the server, or close the terminal window it’s running from.
```suggestion
1. Stop the server if it’s running. You can use the keyboard shortcut <kbd>CTRL-C</kbd> (even on macOS) to stop the server or close the terminal window it’s running from.
```

2024-08-08 20:42 UTC, psybers commented on docs/install/local.md
> +2. Navigate to the Actual Server in your project root director.
```suggestion
2. Navigate to the Actual server in your project root director.
```

2024-08-08 20:42 UTC, psybers commented on docs/install/local.md
> +3. Install all the required dependencies using yarn.
```suggestion
3. Install all the required dependencies using `yarn`.
```

2024-08-08 20:42 UTC, psybers commented on docs/install/local.md
> +1. After the prerequisites are fulfilled, clone the [Actual Server](https://github.com/actualbudget/actual-server) project in your project root directory where you want to install Actual.
```suggestion
1. After the prerequisites are fulfilled, clone the [Actual server](https://github.com/actualbudget/actual-server) project in your project root directory where you want to install Actual.
```

2024-08-08 20:42 UTC, psybers commented on docs/install/local.md
> +Actual Server is the server element of Actual that is used for syncing changes across devices. It comes with the latest version of [Actual Web.](https://github.com/actualbudget/actual)
```suggestion
Actual server is used for syncing changes across devices. It comes with the latest version of the [Actual web client](https://github.com/actualbudget/actual).
```

2024-08-08 20:42 UTC, psybers commented on docs/install/local.md
> +- The Actual Server requires Node.js v18 or greater. You can download and install latest version of the Node.js from [Node.js website](https://nodejs.org/en/download) (we recommend downloading the “L
```suggestion
- The Actual server requires Node.js v18 or greater. You can download and install the latest version of Node.js from [Node.js website](https://nodejs.org/en/download) (we recommend downloading the “LTS” version). 
```

2024-08-12 04:50 UTC, Teprifer reviewed
@MatissJanis Got beaten to it by Psybers. Had a squiz through the suggested changes he has put forward and I'm happy with those so this is good to go once they've been incorporated.

2024-09-14 05:10 UTC, RubenOlsen approved these changes
Cleaning up abandoned PR with good content and incorporating proposed changes from @psybers

2024-09-14 05:29 UTC, RubenOlsen commented on docs/install/local.md
> +The easiest way to get the Actual running on locally is to use the [actual-server](https://github.com/actualbudget/actual-server).
Fixing this during cleanup of abandon PR

2024-09-14 05:31 UTC, RubenOlsen commented on docs/install/local.md
> +- The Actual Server requires Node.js v18 and greater. You can download and install latest version of the Node.js from [Node.js website](https://nodejs.org/en/download) (we recommend downloading the “
Fixed during cleanup of abandoned PR.

2024-09-14 05:40 UTC, merged