basics of text style guide for consistent tone when writing.
actualbudget/docs pull request #398
Opened 2024-07-08 13:41 UTC by wdpk

add some basic guidelines about how to write the docs so a shared voice is heard when using the documentation.

Notes and edits welcome.

2024-07-08 13:57 UTC, RubenOlsen commented
Good one!

You beat me on this one. 

Would it make better sense to have this (also) in the https://actualbudget.org/docs/contributing/ section of the documents itself? As _Contributing to the documentation_ (or some such title)?

Now, the readme.md file is a little bit all over the place - and I would instead we had the technical stuff (as in just how to get docosaurus going, and stuff like that) in the readme - and the language, screenshots, annotation, etc as a proper document.

What do you think about this idea?

2024-07-08 14:03 UTC, wdpk commented
> Good one!
> 
> You beat me on this one.
> 
> Would it make better sense to have this (also) in the https://actualbudget.org/docs/contributing/ section of the documents itself? As _Contributing to the documentation_ (or some such title)?
> 
> Now, the readme.md file is a little bit all over the place - and I would instead we had the technical stuff (as in just how to get docosaurus going, and stuff like that) in the readme - and the language, screenshots, annotation, etc as a proper document.
> 
> What do you think about this idea?

I think this would make sense in the "Contributing" section, and splitting it off from the readme. Maybe make it into a Contributing page and have the readme point to that page?

2024-07-08 14:07 UTC, wdpk commented
invited you as collab but i can make the change myself later

2024-07-18 13:23 UTC, atgrey24 commented
For annotating images, the README says 
> The clearest way to highlight areas on a screenshot is the 'transparency' box.

However the [Writing Documentation](https://deploy-preview-398.www.actualbudget.org/docs/contributing/writing-docs#avoid-using-transparency-or-spotlight-annotations) article says:
> Avoid using transparency or spotlight annotations

The advice between these needs to be consistent.

I also think it would be helpful if the [Formatting Text](https://deploy-preview-398.www.actualbudget.org/docs/contributing/writing-docs#formatting-text) section included examples of how the different styles (tip, note, caution, quote & code) are displayed, similar to how it currently has an example for [Hiding and showing information](https://deploy-preview-398.www.actualbudget.org/docs/contributing/writing-docs#hiding-and-showing--information)

2024-07-20 10:45 UTC, RubenOlsen commented
> For annotating images, the README says 
> 
> > The clearest way to highlight areas on a screenshot is the 'transparency' box.
> 
> 
> 
> However the [Writing Documentation](https://deploy-preview-398.www.actualbudget.org/docs/contributing/writing-docs#avoid-using-transparency-or-spotlight-annotations) article says:
> 
> > Avoid using transparency or spotlight annotations
> 
> 
> 
> The advice between these needs to be consistent.
> 

I assume we have not yet come around to amend the README yet.

2024-07-29 10:33 UTC, RubenOlsen commented
This is now ready for review.

2024-07-30 06:13 UTC, wdpk commented
Thanks Ruben! Marked as RFR

2024-08-08 18:35 UTC, jfdoming reviewed
Couple of thoughts. Thanks for the contributions!

2024-08-08 18:36 UTC, jfdoming commented on README.md
> +Firstly, thank you for stopping by and giving up some of your time to either check out the documentation we have already produced or pick off some of the [issues](https://github.com/actualbudget/docs
nit: to be consistent in this paragraph with capitalization

```suggestion
Firstly, thank you for stopping by and giving up some of your time to either check out the documentation we have already produced or pick off some of the [issues](https://github.com/actualbudget/docs/issues) and help create some new documentation for our future users. Check out the [guidelines](https://actualbudget.org/docs/contributing/writing-docs) for more information on how the documentation is structured and tips for consistent formatting.
```

2024-08-08 20:32 UTC, psybers requested changes

2024-08-09 08:39 UTC, RubenOlsen commented on docs/contributing/writing-docs.md
> +* If you need to address more than one part of the screenshot, annotate the image. See below for more details.
I have not yet seen any use of alt-text in the documentation (which is the reason why I have not added any myself). 

I believe that we should write something that we should encourage the use of alt-text.

2024-08-09 08:39 UTC, RubenOlsen commented on docs/contributing/writing-docs.md
> +All documentation is written in Markdown, and there is a specific Markdown items that is specific to Docusaurus.
Good one - will implement.

2024-08-09 08:40 UTC, RubenOlsen commented on docs/contributing/writing-docs.md
> +`## Sub Headings to split out sections of your document`
I myself prefer Subheadings over Sub Headings.

2024-08-09 08:41 UTC, RubenOlsen commented on README.md
> +Firstly, thank you for stopping by and giving up some of your time to either check out the documentation we have already produced or pick off some of the [issues](https://github.com/actualbudget/docs
I agree. Will fix.

2024-08-09 08:41 UTC, RubenOlsen commented on docs/contributing/writing-docs.md
> +**Using coloured boxes**:
3 people have been invovled in this PR :-D - so this is the reason. I'll take action.

2024-08-09 08:43 UTC, RubenOlsen commented on docs/contributing/writing-docs.md
> +| Blue       | 112, 175, 253 | 70 AF FD |
A very important point, and I'll fix it. 

Is there a tool that lets me check those two?

2024-08-09 08:50 UTC, psybers commented on docs/contributing/writing-docs.md
> +| Blue       | 112, 175, 253 | 70 AF FD |
On Mac I use this: https://apps.apple.com/us/app/sim-daltonism/id693112260?mt=12

This might work on Windows? https://colororacle.org/

2024-08-12 04:18 UTC, RubenOlsen commented on docs/contributing/writing-docs.md
> +| Blue       | 112, 175, 253 | 70 AF FD |
thank a lot, @psybers :-) - this will come in handy in other uses also.

2024-08-17 00:09 UTC, matt-fidd requested changes
Firstly, thank you for this - I belive it's a massive step forward in the documentation process!

Sorry for the volume of comments here, there's a chance that I've been a bit picky in places. Please do feel free to push back on any you don't agree with!

2024-08-17 00:09 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +#### Use "steps" for several elements
We should be consistent in the "Do xxx" and "x" here

Should this be
```suggestion
#### Do use "steps" for several elements
```

or should we drop the "do" from the first?

2024-08-17 00:09 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +a. Formatting numbers. We support most formats that are commonly used.
```suggestion
a. Formatting numbers. We support most commonly used formats.
```

2024-08-17 00:24 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +* For regularly used images, these can be put into `/static/img/elements/`, inside it's own folders. Let's say you want to store images related to the sidebar; then all _sidebar_ images need to be pl
It would be worth bringing in the example of the settings button in the sidebar from the old version for some extra context here

2024-08-17 00:26 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +#### Use "steps" for several elements
We should also clarify the heading

```suggestion
Use "steps" when referring to several elements
```

2024-08-25 20:40 UTC, RubenOlsen commented
> Sorry for the volume of comments here, there's a chance that I've been a bit picky in places. Please do feel free to push back on any you don't agree with!

Nah. They are all good IMO.  I'll implement these so we can get the document out of the door ASAP.  

Thanks for the feedback 😊

2024-08-26 03:25 UTC, RubenOlsen commented on docs/contributing/writing-docs.md
> +Each chapter can then be split into subsections using three-gate headings. Is is also pos
Agree. I also removed "three-gate".

2024-08-26 04:20 UTC, RubenOlsen commented on docs/contributing/writing-docs.md
> +Each chapter can then be split into subsections using three-gate headings. Is is also pos
I have seen the pound sign referred to as a gate in other languages by non IT people. 

In Norway this sign was earlier (late 1980's early 1990s) referred to as a "skigard" (roundpole fence - https://en.wikipedia.org/wiki/Roundpole_fence) sign.

2024-08-26 04:20 UTC, RubenOlsen commented on docs/contributing/writing-docs.md
> +Front matter is used to add metadata to your documentation file. The front matter enriches the default metadata inferred from the content or other configuration.
Agree - and fixed in my rewrite.

2024-08-26 10:08 UTC, RubenOlsen commented
> Firstly, thank you for this - I belive it's a massive step forward in the documentation process!
> 
> Sorry for the volume of comments here, there's a chance that I've been a bit picky in places. Please do feel free to push back on any you don't agree with!

I think I have addresses all your concerns, @matt-fidd

2024-09-03 22:11 UTC, matt-fidd requested changes
A couple more, sorry!

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +
This doesn't look quite right, was it left in by mistake?

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +Below are some basic guidelines on how the documentation should be formatted. Everyone has their own writing style, but the layout of the documents should be the same across all documents.
I think this one's been missed

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +<details><summary>Click here to see how this is made</summary>
What do you think to this suggestion?

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +* A longer filename is preferred over a shorter one.
What do you think to this suggestion?

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +* Except for logos and such, all images related to the documentation must be placed in a folder corresponding to where the document is stored. Let's say you want to add an image to a document in the
What do you think to this suggestion?

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +**Using coloured boxes**:
Looks like this has been missed

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +### Documents Headers
There's a bit of inconsistency between the use of 'headers' and 'headings' here, FWIW I prefer headings.
Could the usage be standardised?

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +### Documents Headers
```suggestion
### Document Headings and Subheadings
```

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +Each document should have only one level 1 heading.
An example

```suggestion
If the title tag is provided, you must omit this level 1 heading.
Each document should have only one level 1 heading.
```

2024-09-03 22:11 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +We follow a strict, mandatory, structure in our documents by using Markdown headers.
```suggestion
We follow a strict, mandatory, structure in our documents by using Markdown headings.
```

2024-09-03 22:13 UTC, matt-fidd commented on docs/contributing/writing-docs.md
> +### Documents Headers
I've added suggestions to let you easily fix if you agree.

2024-09-12 14:24 UTC, RubenOlsen approved these changes

2024-09-13 07:35 UTC, matt-fidd approved these changes
Thank you for putting up with my nit-pickiness!

Looking good 🙌

2024-09-13 07:36 UTC, merged