Pay Distribution Template Docs
actualbudget/docs pull request #417
Opened 2024-07-30 15:28 UTC by Midgetwombat

Added Documentation for the Pay Distribution templates., Ready if the PR [#3078](https://github.com/actualbudget/actual/pull/3078) is accepted.

2024-07-31 14:17 UTC, RubenOlsen requested changes
Good work - just a few nit-pics.

2024-07-31 14:17 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +|#template +10%| Sets a Pay Distribution Template, Each time 'Apply Template' is clicked adds the given percentage from remaining available budget to the category budgeted amount. | Distributes each
Lowercase after the comma, or use a full stop instead of the comma (I prefer this).

Proposed change: Sets a Pay Distribution Template. Each time 'Apply Template' is clicked, the percentage from the remaining available budget is added to the category budgeted amount.

2024-07-31 14:17 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +Pay Distribution templates are used to distribute income across categories, without wiping what has already been budgeted or affecting the category's goal.
- Remove comma after categories.
- _are used to_ can be removed without loosing clarity.

2024-07-31 14:17 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +Each time 'Apply Template' is clicked the available funds will be distributed accordingly.
- Add a comma after _clicked_.
- A proposal to make the language flow a little bit better: _The available funds will be distributed when the 'Apply Template' is clicked._

2024-07-31 14:17 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +- Other Templates that share a category with a Pay Distribution template, will ignore the budgeted column and only set the goals for that category.
Remove the comma after _template_

2024-07-31 14:17 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +- Pay distribution templates can be used in conjunction with Remainder template. By adding `#template +0` before `#template remainder` all remaining budget will be added to the Remainder templates ca
- Uppercase in _Distribution Template_ to keep consistency with the rest of the text.
- Missing _the_ in _conjunction with **the** Remainder template_
- Missing plural in _budget_ in _all remaining budget will be_ as _templates_ are plural elsewhere.

2024-07-31 14:17 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +- Pay distribution templates ignore the `Apply budget template` empty cells rule. This is because Pay distribution templates are designed to add to budgeted amounts regularly.
I suggest shortening this a little bit into: _Pay distribution templates ignore the `Apply budget template` empty cells rule because they are designed to add to budgeted amounts regularly._

2024-07-31 14:17 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +- Pay distribution templates only use available funds, once there are no available funds left in the budget all other Pay distribution will not work.
- Use uppercase in Distribution Template to keep consistency with the rest of the text.
- Suggest using a semicolon after funds rather than a comma because there should be a comma after _budget_.
- Pay distribution -> Pay distributions (plural).

2024-07-31 14:17 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +Pay distribution templates are triggered each time [Apply Budget Templates](#apply-the-templates) is pressed.
Consider using _is clicked_ rather than _is pressed_.

2024-08-01 03:19 UTC, Midgetwombat commented on docs/experimental/goal-templates.md
> +- Pay distribution templates can be used in conjunction with Remainder template. By adding `#template +0` before `#template remainder` all remaining budget will be added to the Remainder templates ca
I've reworded line 217, hopefully making it clearer.

2024-08-01 17:26 UTC, RubenOlsen requested changes

2024-08-01 17:26 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +Pay Distribution templates are designed for budgeting funds not in sync with a monthly budget. People who need to budget each paycheck or don't have the funds to budget for a whole month.
Uppercase T in template to be consistent with rest of the text.

2024-08-01 17:26 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +- Pay Distribution templates will follow goal limits set by other templates on the category.
- Uppercase T in the template to be consistent with the rest of the text.

2024-08-01 17:26 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +- Pay Distribution templates can be used in conjunction with the Remainder template. By adding `#template +0` before `#template remainder` remaining budget will be added to the current budgeted amoun
- Uppercase T in the template to be consistent with the rest of the text.

2024-08-01 17:26 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +- Pay Distribution templates ignore the Apply budget template empty cells rule because they are designed to add to budgeted amounts regularly.
- Uppercase T in the template to be consistent with the rest of the text.

As the sentence now stands, it's difficult to understand. Maybe add some more formatting like:

Pay Distribution Templates ignore the _Apply budget template empty cells rule_ because they are designed to add to budgeted amounts regularly.

2024-08-01 17:26 UTC, RubenOlsen commented on docs/experimental/goal-templates.md
> +- Pay Distribution templates only use available funds; once there are no available funds left in the budget, all other Pay Distributions will not work.
- Uppercase T in the template to be consistent with the rest of the text.
- add _will_ before _only_, as in _will only use_.
- Add Templates after "all other Pay Distribution".

2024-08-02 16:10 UTC, Midgetwombat commented
@RubenOlsen Thanks for your help, as you could probably tell. Documentation isn't my fort, also my English is my only known language. So the only one I get to screw up lol. Appreciate you.

2024-08-02 21:58 UTC, RubenOlsen approved these changes

2024-08-02 21:59 UTC, RubenOlsen commented
Please remove the [WIP] from the summary so that the maintainers can merge these changes

2024-08-03 12:19 UTC, RubenOlsen approved these changes

2024-08-06 02:06 UTC, closed without merging

2024-08-06 02:24 UTC, Midgetwombat commented
I am closing the PR this documentation was for, so no need for this PR.