:bookmark: (24.8.0)
actualbudget/docs pull request #421
Opened 2024-08-02 18:49 UTC by MatissJanis

2024-08-02 18:55 UTC, MatissJanis commented on blog/2024-08-02-release-24.8.0.md
> +- TODO
Any suggestions what to highlight?

2024-08-02 20:42 UTC, twk3 commented on blog/2024-08-02-release-24.8.0.md
> +- TODO
```
- [#2814](https://github.com/actualbudget/actual/pull/2814) Shows favourite and up to the top 5 most frequently used payees in the payee dropdown menu in a section at the top. — thanks @qedi-r
- [#3012](https://github.com/actualbudget/actual/pull/3012) Add long term goal type template — thanks @youngcw
- [#3061](https://github.com/actualbudget/actual/pull/3061) Add additional keyboard hotkeys. — thanks @psybers
- [#3132](https://github.com/actualbudget/actual/pull/3132) In spending report - adding last month as an option for the primary graph — thanks @carkom
```

These are the ones that strike me as positively impacting a broad section of the users

2024-08-02 21:22 UTC, MatissJanis commented on blog/2024-08-02-release-24.8.0.md
> +- TODO
Added most of these! Thanks for the suggestion.

2024-08-02 23:31 UTC, matt-fidd requested changes

2024-08-02 23:31 UTC, matt-fidd commented on blog/2024-08-02-release-24.8.0.md
> +- most used an favorite payees appear at the top of the payee autocomplete results
an -> and

2024-08-03 09:39 UTC, matt-fidd approved these changes

2024-08-03 13:30 UTC, merged