Add i18n documentation
actualbudget/docs pull request #431
Opened 2024-08-13 11:32 UTC by julianwachholz

2024-08-14 04:53 UTC, psybers requested changes

2024-08-14 04:53 UTC, psybers commented on docs/contributing/i18n.md
This file is not in the menu, and thus no one will ever find it unless they guess the URL.

Be sure to also edit https://github.com/actualbudget/docs/blob/master/docs-sidebar.js

2024-08-14 04:53 UTC, psybers commented on docs/contributing/i18n.md
> +You're interested in bringing Actual to a broader audience by translating and localizing the app into new languages? Great! This guide will show you how to get started. Adding translations can be a g
```suggestion
Are you interested in bringing Actual to a broader audience by translating and localizing the app into new languages? Great! This guide will show you how to get started. Adding translations can be a great first step into contributing to open-source software.
```

2024-08-14 04:53 UTC, psybers commented on docs/contributing/i18n.md
> +At this time Actual **is not yet ready** to receive community translations.
I'd recommend making this use the warning box. And possibly moving to the very top of the page.

```suggestion
:::warning

At this time Actual **is not yet ready** to receive community translations.

:::
```

2024-08-14 04:53 UTC, psybers commented on docs/contributing/i18n.md
> +text from the message catalogue.
I still don't know if we are using American or British English for the docs.... but I feel like most of the other pages read like American English.

```suggestion
text from the message catalog.
```

2024-08-14 04:55 UTC, RubenOlsen requested changes

2024-08-14 04:55 UTC, RubenOlsen commented on docs/contributing/i18n.md
> +You're interested in bringing Actual to a broader audience by translating and localizing the app into new languages? Great! This guide will show you how to get started. Adding translations can be a g
I understand the context, but the form is odd. 

Suggestion #1: _If you're interested in bringing..._
Suggestion #2: _Are you interested in bringing..._

2024-08-14 04:55 UTC, RubenOlsen commented on docs/contributing/i18n.md
> +Actual is currently being prepared for internationalization (i18n). This means that originally everything in the app was English, but we're slowly marking all texts for translation.
- Consider using _initially,_ over _originally_
- Suggestion to make the second part of the paragraph a bit more clear: _This means that everything in the app was initially English, but we're slowly marking all texts for translation._

2024-08-14 04:55 UTC, RubenOlsen commented on docs/contributing/i18n.md
> +At this time Actual **is not yet ready** to receive community translations.
Suggestion: _At this time_ => _Currently_.

2024-08-14 04:55 UTC, RubenOlsen commented on docs/contributing/i18n.md
> +Developing translated software requires that every text shown to the user needs to pass through a translation function. Actual uses [i18next](https://www.i18next.com/) to achieve this goal.
Consider removing: _needs to_ to make the sentence shorter.

2024-08-14 04:55 UTC, RubenOlsen commented on docs/contributing/i18n.md
> +
These two sentences should be augmented by examples of what one means by _artificial keys_ vs _natural English_. If one is deep into translating software this is a go-given, but if you have never translated any software before those sentences needs a little bit more explanation.

2024-08-14 17:43 UTC, psybers approved these changes

2024-08-15 16:54 UTC, youngcw approved these changes

2024-08-15 16:54 UTC, merged