Add FAQ entry on how to add GoCardless bank to limited history list.
actualbudget/docs pull request #435
Opened 2024-08-16 18:01 UTC by psybers

Provides steps to contribute to the GoCardless list of banks with limited (90 day) historical data.

2024-08-16 22:08 UTC, RubenOlsen requested changes

2024-08-16 22:08 UTC, RubenOlsen commented on docs/advanced/bank-sync.md
> +2. Toward the top is a link to a Google Docs. Find your bank's ID in that document.
- Either remove the "a" in _a Google Docs_, or _Toward the top is a link to the Google Docs containing data points for the GoCardless integration._
- _Find_ => _Locate_
- _in that_ => _in the_

2024-08-16 22:08 UTC, RubenOlsen commented on docs/advanced/bank-sync.md
> +4. Edit the file `src/app-gocardless/bank-factory.js`.
Between 3 and 4, there should be instruction on creating a branch, right?

2024-08-16 22:08 UTC, RubenOlsen commented on docs/advanced/bank-sync.md
> +6. Commit your changes and push to your fork.
Se comment regarding adding a branch to the fork.

2024-08-16 22:08 UTC, RubenOlsen commented on docs/advanced/bank-sync.md
> +9. Commit your changes and push to your fork.
Ditto from #6

2024-08-16 22:08 UTC, RubenOlsen commented on docs/advanced/bank-sync.md
> +Once reviewed, the maintainers will comment on the pull request and merge it if it is acceptable.  The change would then be available in the next release of the software.
_it is_ can be removed without losing clarity as it makes the sentence slightly shorter.

2024-08-16 22:38 UTC, psybers commented on docs/advanced/bank-sync.md
> +4. Edit the file `src/app-gocardless/bank-factory.js`.
That is optional. If people want to, they can.

2024-08-20 19:36 UTC, youngcw approved these changes

2024-08-20 19:36 UTC, merged