added relinking section
actualbudget/docs pull request #437
Opened 2024-08-18 04:03 UTC by natrlhy

Included steps/links on how to remove linking in Actual, SimpleFIN and re-linking

2024-08-18 04:10 UTC, natrlhy reviewed
Misspelling

2024-08-18 04:30 UTC, natrlhy reviewed
Fixed more wording...

2024-08-19 19:00 UTC, RubenOlsen requested changes

2024-08-19 19:00 UTC, RubenOlsen commented on docs/experimental/simplefin-sync.md
> +6. Save the generated Setup Token someplace safe (one-time use only).
Since it is a one-time token, this sentence seems slightly odd. 

Proposed wording:

```suggestion
6. As you cannot retrieve the Setup Token value later, copy-paste it to a file, as it will be used in step 9. 
```

2024-08-19 19:00 UTC, RubenOlsen commented on docs/experimental/simplefin-sync.md
> +9. You will be asked to enter your SimpleFIN setup token. The keys from this value will be saved on the server, so you will only need to enter it once.
Simplify this sentence. 

Proposed wording:

```suggestion
9. When asked to enter your SimpleFIN Setup Token, use the value you copy-pated in step 6. The token will be saved on the Actual server.
```

2024-08-19 19:00 UTC, RubenOlsen commented on docs/experimental/simplefin-sync.md
> +If you restore an Actual Budget file, it is recommended to unlink and setup the linking again.
It's better to tell people who are unsure of what to do than to suggest what to do :-) 

Proposed rewrite:
```suggestion
When restoring an Actual Budget file from a backup, the recommended practice is to unlink the SimpleFIN sync and then set it up again.```

2024-08-19 19:00 UTC, RubenOlsen commented on docs/experimental/simplefin-sync.md
> +1. Unlink accounts in your Actual budget file. Do this for all accounts linked. The SimpleFIN token is a one-time use token.
```suggestion
1. Unlink all linked accounts in your Acutal Budget: Click on an account, use the ... (kebab menu) in the top right and choose _Unlink Account_.
```

2024-08-19 19:00 UTC, RubenOlsen commented on docs/experimental/simplefin-sync.md
> +   - **_For an existing account, click on that account, select the ... (kebab menu) in the top right, and choose Unlink account_**
Remove this sentence as it's added to the previous.

2024-08-19 19:00 UTC, RubenOlsen commented on docs/experimental/simplefin-sync.md
> +2. Reset the SimpleFIN credentials by clicking on “+ Add account” at the bottom of the sidebar.
Use instructional active voice.

```suggestion
2. To reset the SimpleFIN credentials, click on “+ Add account” at the bottom of the sidebar.
```

2024-08-19 19:00 UTC, RubenOlsen commented on docs/experimental/simplefin-sync.md
> +   ![Screenshot 2024-08-17 164607](https://github.com/user-attachments/assets/a9c726da-cb5f-4188-915c-27fca3ee5cb7)
Is this the correct screen shot saved in the repo?

2024-08-19 19:00 UTC, RubenOlsen commented on docs/experimental/simplefin-sync.md
> +4. Skip to step 5 in the [SimpleFIN Setup](https://actualbudget.org/docs/experimental/simplefin-sync#simplefin-setup) section to create another App token.
Use active voice for instructions.

```suggestion
4. To create another app token, skip to step 5 in the [SimpleFIN Setup](/docs/experimental/simplefin-sync#simplefin-setup) section.
```

2024-08-19 19:00 UTC, RubenOlsen commented on docs/experimental/simplefin-sync.md
> +5. Follow the steps in the [Link Accounts to SimpleFIN](https://actualbudget.org/docs/experimental/simplefin-sync#link-accounts-with-simplefin) section to link accounts again.
```suggestion
5. To link accounts again, follow the steps in the [Link Accounts to SimpleFIN](/docs/experimental/simplefin-sync#link-accounts-with-simplefin) section.
```

2024-10-07 18:36 UTC, RubenOlsen commented
Pr closed due to inactivity from the comitter for more than 4 weeks.

2024-10-07 18:36 UTC, closed without merging