#470 - added section on Pay Yourself First strategy
actualbudget/docs pull request #473
Opened 2024-10-14 16:47 UTC by RubenOlsen

A go at #470

2024-10-18 17:14 UTC, youngcw commented
I think it would be good to give a brief example of how to do this, not just what it is.  Also my blog post from last year shows how I do this with templates if you want to link there.

2024-10-19 08:51 UTC, RubenOlsen commented
Good point! I see where you are coming from and I did think about adding a brief example. 

However - I wanted to keep it as short as the *Month Ahead* strategy. For now, I'll add an example and also link to the blogpost. I'll see if I also can add a brief example in the month ahead paragraph.

2024-11-03 16:20 UTC, matt-fidd requested changes
Minor nit for consistency

2024-11-03 16:20 UTC, matt-fidd commented on docs/getting-started/envelope-budgeting.md
> +For example, if you make € 3,000 this month, instead of spending it on this month's bills, you save it and use it to
We should probably keep to `$` as the currency of choice in the docs, not that it particularly matters, just to standardise.

2024-11-04 21:11 UTC, youngcw commented on docs/getting-started/envelope-budgeting.md
> +For example, if you make € 3,000 this month, instead of spending it on this month's bills, you save it and use it to
are we consistent other places?

2024-11-27 19:27 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +For example, if you make € 3,000 this month, instead of spending it on this month's bills, you save it and use it to
AFAIK we are not consistent in other places. 

I see the point of being consistent here :-)

I'll fix this and also go through the rest of the documentation to see if this is an issue other places.

2025-01-03 07:19 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +For example, if you make € 3,000 this month, instead of spending it on this month's bills, you save it and use it to
The currency symbol comment has been resolved for  both the file in this PR and also one more place.

2025-01-03 12:24 UTC, RubenOlsen commented
@matt-fidd roasting time again :-)

2025-01-03 17:31 UTC, youngcw commented on docs/getting-started/envelope-budgeting.md
> +Giving every dollar a job forces you to be honest about where you money is going because each dollar can
Why did this change?  It was correct before

2025-01-03 17:31 UTC, youngcw commented on docs/getting-started/envelope-budgeting.md
> +1. **Identify Irregular Expenses**: List of all large, infrequent expenses you expect throughout the year.
This also seems wrong now.  I think the existing is better.

2025-01-03 17:31 UTC, youngcw commented on docs/getting-started/envelope-budgeting.md
> +**Example:** Let’s say your annual insurance costs are $ 2 400. Instead of scrambling to find this amount when the bill
If we are going for consistently $ numbers then we should also be consistent with the thousands separators.  Before there were commas, now its changed to spaces.  Probably should stick with commas.

2025-01-03 17:31 UTC, youngcw commented on docs/getting-started/envelope-budgeting.md
> +in your bank statement. Bank and credit card statement statements provide a detailed history of your
this should just be reverted.

2025-01-03 17:31 UTC, youngcw commented on docs/getting-started/envelope-budgeting.md
> +## An detailed example of how to do Zero-Sum budgeting
revert this

2025-01-03 17:31 UTC, youngcw commented on docs/getting-started/envelope-budgeting.md
> +Let's say your total monthly income of January is $ 1 200. You get your money on the 1st.  Using Zero-Based Budgeting,
probably "total monthly income _in_ January".  Also its a space separator again

2025-01-03 17:31 UTC, youngcw commented on docs/getting-started/envelope-budgeting.md
> +Here's an example of how you could split the $ 1 200:
separator

2025-01-04 08:59 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +Giving every dollar a job forces you to be honest about where you money is going because each dollar can
I have no idea why. Changing it back.

2025-01-04 09:01 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +1. **Identify Irregular Expenses**: List of all large, infrequent expenses you expect throughout the year.
I agree with you - and I have still no idea why this happened.

2025-01-04 09:03 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +**Example:** Let’s say your annual insurance costs are $ 2 400. Instead of scrambling to find this amount when the bill
I do not agree with this. 

To separate thousands, the [International Bureau of Weights and Measures](https://www.bipm.org/en/home) revealed that the right way to write numbers with over four figures is by dividing them into groups of three and leaving a space between them. 

Despite this, it’s still often in nations that use decimal commas to find thousands separated by a dot. A comma is commonly used to separate thousands in countries where a point is used as a decimal separator.

2025-01-04 09:04 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +in your bank statement. Bank and credit card statement statements provide a detailed history of your
Agree.

2025-01-04 09:05 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +## An detailed example of how to do Zero-Sum budgeting
Agree

2025-01-04 09:05 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +Let's say your total monthly income of January is $ 1 200. You get your money on the 1st.  Using Zero-Based Budgeting,
Agree on "in" - fixing.

2025-01-04 09:06 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +Here's an example of how you could split the $ 1 200:
See above :-)

2025-01-04 16:08 UTC, matt-fidd commented on docs/getting-started/envelope-budgeting.md
> +**Example:** Let’s say your annual insurance costs are $ 2 400. Instead of scrambling to find this amount when the bill
I prefer the commas here too. As we're sticking with US-isms I'd say that we should use the commonly seen separator too.

2025-01-05 06:03 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +**Example:** Let’s say your annual insurance costs are $ 2 400. Instead of scrambling to find this amount when the bill
Ok then - I succumb to the peer pressure :-D

2025-01-06 18:35 UTC, youngcw approved these changes

2025-01-06 22:00 UTC, matt-fidd approved these changes

2025-01-08 18:53 UTC, merged