Use consistent terms regarding on-budget and off-budget accounts
actualbudget/docs pull request #504
Opened 2024-11-26 18:53 UTC by joel-jeremy

2024-11-27 19:03 UTC, RubenOlsen commented
@joel-jeremy  please resolve the branch conflicts.

2024-11-28 20:49 UTC, RubenOlsen requested changes

2024-11-28 20:49 UTC, RubenOlsen commented on docs/accounts/index.md
> +Depending on your usage, savings accounts can either be on or off the budget. If you're not sure, we recommend keeping it on-budget at the start.
```suggestion
Depending on your usage, savings accounts can be on or off the budget. If you're not sure, we recommend keeping them on budget at the start.
```

2024-11-28 20:49 UTC, RubenOlsen commented on docs/getting-started/envelope-budgeting.md
> +Giving every dollar a job forces you to be honest about where you money is going because each dollar can
Was this an oversight to have *you money* instead of keeping *your*?

2024-12-10 21:46 UTC, matt-fidd commented
The images will need updating to remove the hyphens now too, sorry!

2025-01-03 07:25 UTC, RubenOlsen approved these changes

2025-01-03 07:25 UTC, RubenOlsen commented
I have approved my own changes as this became stale.

2025-01-03 07:26 UTC, merged